# build.yaml
include:
  # Normalne buildy (bez Studio)
  - board: nice_nano_v2
    shield: ferris_rev02_left
    artifact-name: ferris_left
  - board: nice_nano_v2
    shield: ferris_rev02_right
    artifact-name: ferris_right

  # Wersje ze Studio (USB-UART)
  - board: nice_nano_v2
    shield: ferris_rev02_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ferris_left_studio
  - board: nice_nano_v2
    shield: ferris_rev02_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ferris_right_studio
